### PR TITLE
Fixing mocks for interfaces where method returns function with variadic argument.

### LINKED ISSUE #707: Wrong code generation when using ellipsis
Description
-------------

Interface and function with ellipsis is not respected

Mockery Version
--------

2.33.2

Golang Version
--------------

1.21.1

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [X] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Create a file with following definition
```go
type ExposedFunction = func(args ...interface{}) interface{}

type Sample interface {
	ExposeFunction(name string, binding ExposedFunction) error
}

func TestMock() {
	t := &testing.T{}
	mock := mocks.NewMockSample(t)

	var _ Sample = mock
}
```

The line for interface implementation testing `var _ Sample = mock` triggers an error : 

```
cannot use mock (variable of type *mocks.MockSample) as Sample value in variable declaration: *mocks.MockSample does not implement Sample (wrong type for method ExposeFunction)
		have ExposeFunction(string, func([]interface{}) interface{}) error
		want ExposeFunction(string, func(...interface{}) interface{}) 
```

There is a difference and it brokes for using mocks.

Here is the generated code by mockery

```go
// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSample is an autogenerated mock type for the Sample type
type MockSample struct {
	mock.Mock
}

type MockSample_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSample) EXPECT() *MockSample_Expecter {
	return &MockSample_Expecter{mock: &_m.Mock}
}

// ExposeFunction provides a mock function with given fields: name, binding
func (_m *MockSample) ExposeFunction(name string, binding func([]interface{}) interface{}) error {
	ret := _m.Called(name, binding)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func([]interface{}) interface{}) error); ok {
		r0 = rf(name, binding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSample_ExposeFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExposeFunction'
type MockSample_ExposeFunction_Call struct {
	*mock.Call
}

// ExposeFunction is a helper method to define mock.On call
//   - name string
//   - binding func([]interface{}) interface{}
func (_e *MockSample_Expecter) ExposeFunction(name interface{}, binding interface{}) *MockSample_ExposeFunction_Call {
	return &MockSample_ExposeFunction_Call{Call: _e.mock.On("ExposeFunction", name, binding)}
}

func (_c *MockSample_ExposeFunction_Call) Run(run func(name string, binding func([]interface{}) interface{})) *MockSample_ExposeFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func([]interface{}) interface{}))
	})
	return _c
}

func (_c *MockSample_ExposeFunction_Call) Return(_a0 error) *MockSample_ExposeFunction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSample_ExposeFunction_Call) RunAndReturn(run func(string, func([]interface{}) interface{}) error) *MockSample_ExposeFunction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSample creates a new instance of MockSample. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSample(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSample {
	mock := &MockSample{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
```

### Expected Behavior

Expect mock to be generated using ellipsis : 

```go
// ExposeFunction provides a mock function with given fields: name, binding
func (_m *MockSample) ExposeFunction(name string, binding func(...interface{}) interface{}) error {
	ret := _m.Called(name, binding)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(...interface{}) interface{}) error); ok {
		r0 = rf(name, binding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
```

### Actual Behavior

Generated with slice `[]`

```go
// ExposeFunction provides a mock function with given fields: name, binding
func (_m *MockSample) ExposeFunction(name string, binding func([]interface{}) interface{}) error {
	ret := _m.Called(name, binding)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func([]interface{}) interface{}) error); ok {
		r0 = rf(name, binding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
```

### PR DESCRIPTION
**Pull request by nicovak**
Description
-------------

Adding a Variadic fixtures to handle signatures with that case

- Fixes #707 and #431 
- Fixing whitespace and format in yml

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

Version of Golang used when building/testing:
---------------------------------------------

- [X] 1.20

How Has This Been Tested?
---------------------------

- Adding fixtures with case and assert output directly in mocks folder, `I may need help or guidance for this one`.

Checklist
-----------

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: pkg/fixtures/variadic.go [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package test
+
+type VariadicFunction = func(args1 string, args2 ...interface{}) interface{}
+
+type Variadic interface {
+	VariadicFunction(str string, vFunc VariadicFunction) error
```
Comment (LandonTClipp) [inline pkg/fixtures/variadic.go:6]: I don't think this is testing the original issue. 

https://github.com/vektra/mockery/issues/431

The issue was with methods that return a function in which one of the arguments is variadic:

```
LogMethodf(level Level) func(message string, a ...interface{})
```

File: pkg/generator.go [hunk 2]
```diff
@@ -562,13 +562,22 @@ func (g *Generator) renderType(ctx context.Context, typ types.Type) string {
...
 	for i := 0; i < tup.Len(); i++ {
 		v := tup.At(i)
 
-		parts = append(parts, g.renderType(ctx, v.Type()))
+		if variadic {
+			switch t := v.Type().(type) {
+			case *types.Slice:
+				parts = append(parts, "..."+g.renderType(ctx, t.Elem()))
+			default:
+				parts = append(parts, g.renderType(ctx, v.Type()))
```
Comment (LandonTClipp) [inline pkg/generator.go:576]: Is it possible for an argument to be variadic but not a slice?

**Comment by LandonTClipp** [comment]
Thank you for sending in a PR. A few questions in the comments.

File: pkg/generator.go (hunk 2 above)
Comment (nicovak) [reply pkg/generator.go:576]: It looks like the variadic is true if one of args is variadic , so if we have multiple arguments, they will each pass in the for loop and we need to handle type

File: pkg/fixtures/variadic.go (hunk 1 above)
Comment (nicovak) [reply pkg/fixtures/variadic.go:6]: I just tested It and It looks like it works, I will push a change to show It

File: pkg/generator.go (hunk 2 above)
Comment (nicovak) [reply pkg/generator.go:576]: See logs here

```
func (g *Generator) renderTypeTuple(ctx context.Context, tup *types.Tuple, variadic bool) string {
	var parts []string

	for i := 0; i < tup.Len(); i++ {
		v := tup.At(i)

		if variadic {
			log.Debug().Msgf("%+v", v.Type())
```

```
{"level":"debug","time":"2023-10-13T10:49:31+02:00","message":"string"}
{"level":"debug","time":"2023-10-13T10:49:31+02:00","message":"[]interface{}"}
{"level":"debug","time":"2023-10-13T10:49:31+02:00","message":"string"}
{"level":"debug","time":"2023-10-13T10:49:31+02:00","message":"[]interface{}"}
{"level":"debug","time":"2023-10-13T10:49:31+02:00","message":"string"}
{"level":"debug","time":"2023-10-13T10:49:31+02:00","message":"[]interface{}"}
```

**Comment by nicovak** [comment]
> Thank you for sending in a PR. A few questions in the comments.

You are welcome, I answered them and just pushed the case for #401 which works with my original code

File: pkg/generator.go (hunk 2 above)
Comment (LandonTClipp) [reply pkg/generator.go:576]: What happens if you have a function signature like this?

```go
func Foo(s []any, i ...int)
```
The `s` argument would match the `*types.Slice` case because it's  a slice, but it's not the variadic arg right?

Comment (nicovak) [reply pkg/generator.go:576]: Yes good catch, I think we will have an error, but I think that Variadic information is not available for each arg
https://github.com/vektra/mockery/blob/e7c0bd979c493313b30aea4cf414da99be1bfcec/pkg/generator.go#L451
Any idea ?

Comment (LandonTClipp) [reply pkg/generator.go:576]: The variadic argument will always be the last one so you can probably just say 

```go
if variadic && i == tupl.Len()-1 {
```

File: pkg/fixtures/variadic.go (hunk 1 above)
Comment (LandonTClipp) [reply pkg/fixtures/variadic.go:6]: Oh sorry I misread this. Yes this is good 👍🏻

**Comment by egeucak** [comment]
are there plans to merge this? i am also facing an issue with variadic arguments

**Comment by LandonTClipp** [comment]
@egeucak I believe we are still waiting on @nicovak to address my last [comment](https://github.com/vektra/mockery/pull/719#discussion_r1362888970). It's very close to being done but we just need someone to address that thread.

**Comment by nicovak** [comment]
I will try to fix It this week

**Comment by nicovak** [comment]
@LandonTClipp @egeucak I rebased and push with the fix we were talking about.
Should be fine now, I added the case about array in `VariadicExtra` Interface

**Comment by LandonTClipp** [comment]
Great, thank you @nicovak ! Could you add a test next to `pkg/fixtures/variadic.go` that uses the generated mock object to ensure we can specify the return argument we expect? You might need to place the mock implementation next to `pkg/fixtures/variadic.go` (instead of in the `mocks/` subdirectory) due to circular import issues.

**Comment by mapkon** [comment]
When will this be merged?

**Comment by LandonTClipp** [comment]
We need tests for this particular case. I believe my last comment is still pending. How big of a blocker is this for you? I can probably finish it out myself.

**Comment by mapkon** [comment]
> We need tests for this particular case. I believe my last comment is still pending. How big of a blocker is this for you? I can probably finish it out myself.

We have a pending PR, that we can't merge unless this is fixed.

**Comment by LandonTClipp** [comment]
> We have a pending PR, that we can't merge unless this is fixed.

Okay I will just complete it tomorrow.

**Review by LandonTClipp — APPROVED** [review]

**Comment by LandonTClipp** [comment]
I submitted the remaining fixes I wanted and assured this works correctly. Will merge in a few moments!

**Comment by nicovak** [comment]
Thank you @LandonTClipp , I didn't have time to work on It these days and I think I would not have been able to implement the tests quicky.

**Comment by LandonTClipp** [comment]
> Thank you @LandonTClipp , I didn't have time to work on It these days and I think I would not have been able to implement the tests quicky. 

No worries at all, we're all busy nowadays. Teamwork makes the dream work and all 😉
