### PR TITLE
Ditch pathlib and fix Windows bugs

### LINKED ISSUE #1001: Unable to generate mocks on Windows due to \\C: in the path
Hi,
I am unable to generate mocks even with very simple setup on windows. I've used DB example from docs and generated config with `mockery init ...`

```pwsh
mockery init github.com/miroslav-matejovsky/mockery-bug
mockery
```

Result:

```text
2025-04-13T04:02:42.382637600+02:00 INF Starting mockery config-file="C:\\Users\\Miroslav.Matejovsky\\dev\\personal\\mockery-bug\\.mockery.yml" version=v3.1.0                                             
2025-04-13T04:02:42.383161800+02:00 INF Parsing configured packages... version=v3.1.0                                                                                                                      
2025-04-13T04:02:42.945495000+02:00 INF Done parsing configured packages. version=v3.1.0                                                                                                                   
2025-04-13T04:02:42.946030700+02:00 INF adding interface to collection collection="C:\\Users\\Miroslav.Matejovsky\\dev\\personal\\mockery-bug\\mocks_test.go" interface=DB package-path=github.com/miroslav-matejovsky/mockery-bug version=v3.1.0
2025-04-13T04:02:42.946560000+02:00 ERR failed to find output package path error="mkdir C:\\Users\\Miroslav.Matejovsky\\dev\\personal\\mockery-bug\\C:: The filename, directory name, or volume label syntax is incorrect." file="C:\\Users\\Miroslav.Matejovsky\\dev\\personal\\mockery-bug\\mocks_test.go" out-pkg-name=main outPkgFSPath="C:\\Users\\Miroslav.Matejovsky\\dev\\personal\\mockery-bug" src-pkg-name=main srcPkgFSPath="C:\\Users\\Miroslav.Matejovsky\\dev\\personal\\mockery-bug" version=v3.1.0
2025-04-13T04:02:42.947086600+02:00 FTL app failed error="mkdir C:\\Users\\Miroslav.Matejovsky\\dev\\personal\\mockery-bug\\C:: The filename, directory name, or volume label syntax is incorrect." version=v3.1.0
```

Repo with my setup: https://github.com/miroslav-matejovsky/mockery-bug

### LINKED ISSUE #1037: v3: generation can add cyclical self import on Windows
## Description

On Windows, the generated mock imports the package in which it is generated, thereby creating an import cycle and preventing compilation.

## Reproducer

Sample application here: https://github.com/davidbacisin/mockery-bug

The generated mock file begins with:

```go
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	"github.com/davidbacisin/mockery-bug"
	mock "github.com/stretchr/testify/mock"
)
```

The debug logs indicate a mismatch in forward vs backslashes, so it thinks that the imported package is different from itself:

```
2025-05-06T13:55:50.517813800-07:00 DBG path does not equal dst-pkg-path, adding import dst-pkg-path="github.com\\davidbacisin\\mockery-bug" file=sample_mock.go interface-name=Sample method=AddImport mock-name=MockSample package-path=github.com/davidbacisin/mockery-bug schema=testify.schema.json src-pkg-path=github.com/davidbacisin/mockery-bug template=testify version=v3.2.5
```

## Expected behavior

The generated mock should compile without errors. It should not import its own package.

## Mockery version

`v3.2.5`

## Installation Mechanism
- [x] Pre-built release

## Go version

1.24.2

### LINKED ISSUE #1060: Mockery generating invalid code on Windows
## Description

When generating a mock into the same package for an interface that uses types from the same package, mockery refers to those types with a qualified name instead of the plain name. This leads to a mock file with an import cycle.

## Reproducer

See https://github.com/kgadams/mockerybug. The generated mock_itf_test.go imports mockerybug and uses mockerybug.Struct instead of Struct.

This is the same behaviour as in #1056. The fix only works on Unix and Mac, but not on Windows.

Excerpt of the log:
```
2025-06-02T10:23:19.222414200+02:00 DBG creating new interface collection file-path=mock_itf_test.go version=v3.3.2
2025-06-02T10:23:19.223389000+02:00 DBG &{githbub.com/kgadams/mockerybug 0xc0002ba5c0 0xc000105040 mockerybug [0xc000312730] testify} file=mock_itf_test.go interfaces-in-file-len=1 version=v3.3.2
2025-06-02T10:23:19.237056200+02:00 DBG can't make path relative to working dir, setting to './' error=". does not start with D:\\mockerybug: failed to make path relative to other" interface-dir-relative-path=. interfaceDirPath=. version=v3.3.2 working-dir="D:\\mockerybug"
2025-06-02T10:23:19.239010900+02:00 DBG output package detected to be in-package of original package file=mock_itf_test.go out-pkg-name=mockerybug outPkgFSPath="D:\\mockerybug" outPkgPath="githbub.com\\kgadams\\mockerybug" src-pkg-name=mockerybug srcPkgFSPath="D:\\mockerybug" version=v3.3.2
```

Backslashes are not taken into account.

## Expected behavior

The parameter to `itf.Use(*Struct)` should be referred to as `*Struct`, not `*mockerybug.Struct`.

## Mockery version

`v3.3.2`

## Installation Mechanism

- [x] `go get -tool`
- [] Pre-built release
- [] homebrew
- [] Other: [please describe]

## Go version

go1.24.3.

### PR DESCRIPTION
**Pull request by kgadams**
Description
-------------

This PR gets rid of the pathlib, replacing all calls with calls to the std library.

No change in generated files, no new warnings, no test errors. A couple of new Unittests.

- Fixes #1001
- Fixes #1037
- Fixes #1060

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Version of Go used when building/testing:
---------------------------------------------

- [ ] 1.22
- [ ] 1.23
- [x] 1.24

How Has This Been Tested?
---------------------------

I tested the code on Mac running the defaults from the Taskfile, and I tested the reproducers from the three issues below on Windows. All of them work now.

Testing on Windows does not work from the taskfile, it assumes a lot of unix tools. I ran the tests manually as far as possible.

Checklist
-----------

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: template_funcs/funcmap.go [hunk 1]
```diff
@@ -58,9 +58,9 @@ var FuncMap = template.FuncMap{
 	"quoteMeta":   regexp.QuoteMeta,
 
 	// Filepath manipulation
-	"base":     filepath.Base,
-	"clean":    filepath.Clean,
-	"dir":      filepath.Dir,
+	"base":     func(path string) string { return filepath.ToSlash(filepath.Base(path)) },
+	"clean":    func(path string) string { return filepath.ToSlash(filepath.Clean(path)) },
+	"dir":      func(path string) string { return filepath.ToSlash(filepath.Dir(path)) },
```
Comment (LandonTClipp) [inline template_funcs/funcmap.go:63]: Is this correct? Why would you want this? If I'm reading correctly this will replace all `\` characters in the Windows path with `/`.

**Review by LandonTClipp — COMMENTED** [review]
Looks great overall, thank you! Just one question on the template func changes.

I wonder if you can try adding windows to the testing matrix. I am 90% confident it won't just work out of the box but I am curious to try. If it's too much trouble for you, we can try it in a different PR.

File: template_funcs/funcmap.go (hunk 1 above)
Comment (kgadams) [reply template_funcs/funcmap.go:63]: First of all, it makes the unittests pass.
Joke aside: in all of my coding I keep pathes with slashes on all platforms. It works just fine on Windows.
Also it makes life easier for the writers of the templates: they can rely on all pathes having slashes as separator, so you don't have to write template variants for different platforms.

**Comment by kgadams** [comment]
> Looks great overall, thank you! Just one question on the template func changes.
> 
> I wonder if you can try adding windows to the testing matrix. I am 90% confident it won't just work out of the box but I am curious to try. If it's too much trouble for you, we can try it in a different PR.

I am not familiar with the testing infrastructure on the public github, normally I work in a corporate github, where this works very much in a different way.
That being said: your scripting already has problems on Windows in relying on a unix shell and on unix commandline utilities... Just running `task` fails miserably (`xargs not found` etc.).

File: template_funcs/funcmap.go (hunk 1 above)
Comment (LandonTClipp) [reply template_funcs/funcmap.go:63]: Interesting, so the tests don't pass unless you use `filepath.ToSlash`? I would be curious to know why. I am just suspicious of this change because someone might, for example, want to read the contents of a file (copyright text, for example), the path of which might need to pass through one of these functions. I don't know if Windows would understand you trying to open a file with `/` characters.

Kind of sad that the Go Playground does not seem to have Windows environments I can test this out with.

Comment (kgadams) [reply template_funcs/funcmap.go:63]: The unittests in `funcmap_test.go` for these template functions expect the result to contain slashes (`/home/file.txt`). Without the change, you get `\home\file.txt` as result, from the `clean` template function test. So you would have to have OS-specific unittests.
Believe you me, nobody wants this.
And go APIs on Windows work just fine with slashes (C APIs too for that matter). Only when you build actual commandlines for consumption by `cmd.exe` do you need backslashes.

Comment (kgadams) [reply template_funcs/funcmap.go:63]: BTW: everywhere pathes are now stored in the coding in my PR, they are stored after conversion to slashes. As mentioned, opening files etc. works just fine with these on Windows.

Comment (LandonTClipp) [reply template_funcs/funcmap.go:63]: I see, thank you for explaining. I am obviously wholly unfamiliar with Windows development! I'll approve and merge/release this in a few. Thanks again for the effort, I needed a Windows dev to help with these problems.

**Comment by kgadams** [comment]
> > Looks great overall, thank you! Just one question on the template func changes.
> > I wonder if you can try adding windows to the testing matrix. I am 90% confident it won't just work out of the box but I am curious to try. If it's too much trouble for you, we can try it in a different PR.
> 
> I am not familiar with the testing infrastructure on the public github, normally I work in a corporate github, where this works very much in a different way. That being said: your scripting already has problems on Windows in relying on a unix shell and on unix commandline utilities... Just running `task` fails miserably (`xargs not found` etc.).

Ok, I added `windows-latest` into the test matrix and fixed the remaining issues. Two forgotten `file.Close()` and some updates in the `Taskfile.yml` to make it work on Windows. It turns out that bash is available on the Windows runners, so the e2e scripts work.

**Comment by LandonTClipp** [comment]
Wow you've gone above and beyond, that's spectacular. Thank you!

**Review by LandonTClipp — APPROVED** [review]
