### PR TITLE
cmd: respect TERM=dumb by not using colors

### LINKED ISSUE #510: cmd: prints escape sequences for colors in terminals with no color support
Description
-------------

`mockery` prints ANSI escape sequences for colors in terminals with no support for them.

Mockery Version
--------

v2.14.0

Golang Version
--------------

`go version go1.19.1 darwin/arm64`

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Open `9term`, `eshell`, a `win $SHELL` window in [Acme](http://acme.cat-v.org/) or any other `TERM=dumb` environment for a terminal.
2. Run `mockery`
3. Observe the output

Note: this is because the `terminal.IsTerminal` check reports `true` for the file descriptor referring to the terminal, but not all terminals support colors. The PR for this issue addresses this by explicitly checking for `TERM=dumb`

### Expected Behavior

ANSI escape sequences for colors are not printed

### Actual Behavior

ANSI escape sequences for colors are printed

### PR DESCRIPTION
**Pull request by acln0**
Description
-------------

Check for `TERM=dumb` when determining whether to use colors when printing.

Fixes #510 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Version of Golang used when building/testing:
---------------------------------------------

- [ ] 1.11
- [ ] 1.12
- [ ] 1.13
- [ ] 1.14
- [ ] 1.15
- [ ] 1.16
- [ ] 1.17
- [ ] 1.18
- [x] 1.19

How Has This Been Tested?
---------------------------

Per #510, I tested by inspecting the output, which no longer contains colors.

Checklist
-----------

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: cmd/mockery.go [hunk 1]
```diff
@@ -297,7 +297,7 @@ func getLogger(levelStr string) (zerolog.Logger, error) {
 		Out:        out,
 		TimeFormat: time.RFC822,
 	}
-	if !terminal.IsTerminal(int(out.Fd())) {
+	if !terminal.IsTerminal(int(out.Fd())) || os.Getenv("TERM") == "dumb" {
```
Comment (LandonTClipp) [inline cmd/mockery.go:300]: I'd prefer this to be pulled in as a config value that can be bound to an env var like `MOCKERY_DISABLE_COLORING`.

**Review by LandonTClipp — APPROVED** [review]
